### ISSUE TITLE
Ensure that upper and lowercase ships does not effect ship placement

### ISSUE THREAD

**Issue by freischj** [cs361fall2018/project-team-20#23]
It is possible the placing a BATTLESHIP vs a battleship vs a BaTtLeShIp causes issues in the ship constructor

**Comment by zeiglers** [comment]
In the ship class, the constructor makes whatever is passed in all CAPS, so this should not be a problem.

**Comment by freischj** [comment]
There are no test cases

**Comment by zeiglers** [comment]
There were when I called my portion done yesterday.

**Comment by zeiglers** [comment]
When I initially wrote the test cases, I ensured each call to make a new ship used a different case combination.

**Comment by bitterplant** [comment]
Made test cases
